project-origin/wallet

doc/adr/0001-Programming-langauge.md
doc/adr/0002-Dapper.md
doc/adr/0003-gRPC.md
doc/adr/0004-CQRS.md
doc/adr/0005-structured-logging.md
doc/adr/0006-open-telemetry.md
doc/adr/README.md

We have talked through some of the ADR for how we want to develop the service for now.
We documented this in the following 6 ADRs:
- Programming Language -> C#/.Net
- Orm -> Dapper
- Protocol -> gRPC
- CQRS
- Structured logging
- Open telemetry

Added ADRs

---

.github/release.yml

This PR adds categories when generating release notes.

Added release note categories

---

src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/RegistryFixture.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TransferCertificateTests.cs
src/ProjectOrigin.WalletSystem.Server/Activities/TransferPartialSliceActivity.cs
src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj

Updated to registry 0.2.0

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ReceiverDepositEndpointTests.cs
src/ProjectOrigin.WalletSystem.Server/Services/WalletService.cs

Fixes #58 where a user could create a reference to own deposit endpoints.

Added guard against self reference in DepositEndpoints

---

src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/CertificateRepositoryTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TransferCertificateTests.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs

Query on slice state

---

src/Protos/wallet.proto

Renamed everything in the .proto  files to follow [best practices](https://protobuf.dev/programming-guides/style/) 
These still compile to the same names, so no other changes are required

Protobuf best practices

---

Makefile
charts/project-origin-wallet/templates/service-wallet.yaml
charts/project-origin-wallet/values.yaml

Added support to configure Service type for helm chart

Enables configuration of service type in helm

---

.github/workflows/sonarcloud.yaml
src/ProjectOrigin.WalletSystem.IntegrationTests/ReceiveSliceTests.cs

Here is a link to the report generated for this PR: https://sonarcloud.io/summary/new_code?id=project-origin_wallet&pullRequest=89

Added SonarCloud GitHub workflow to analyse code 

---

src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/ClaimTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/AbstractRepositoryTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/CertificateRepositoryTests.cs
src/ProjectOrigin.WalletSystem.Server/Extensions/TimestampExtensions.cs
src/ProjectOrigin.WalletSystem.Server/Models/CertificateAttribute.cs
src/ProjectOrigin.WalletSystem.Server/Models/CertificateType.cs
src/ProjectOrigin.WalletSystem.Server/Models/CertificateViewModel.cs
src/ProjectOrigin.WalletSystem.Server/Models/ClaimFilter.cs
src/ProjectOrigin.WalletSystem.Server/Models/ClaimViewModel.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/ICertificateRepository.cs
src/ProjectOrigin.WalletSystem.Server/Services/WalletService.cs
src/Protos/wallet.proto

Claims can now be queried from the wallet system, it allows filtering based on start and end date.
fixes #42

Added Query claims with filter

---

src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/PostgresFixtureExtensions.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TransferCertificateTests.cs
src/ProjectOrigin.WalletSystem.Server/Activities/TransferPartialSliceActivity.cs

Fixed wrong index for remainder on partial-transfer

---

.github/workflows/renovate.yaml

Changed to use GitHub App to get seperate comitter from me.

Update Renovate GitHub Action to v39.1.1

---

charts/project-origin-wallet/templates/deployment-wallet.yaml
charts/project-origin-wallet/values.yaml
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiBasePathTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.cs
src/ProjectOrigin.WalletSystem.Server/Options/RestApiOptions.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/PathBaseDocumentFilter.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
src/ProjectOrigin.WalletSystem.Server/Startup.cs

Add configurable path base

---

charts/project-origin-wallet/templates/service-wallet.yaml
src/ProjectOrigin.WalletSystem.Server/Startup.cs
src/ProjectOrigin.WalletSystem.Server/appsettings.json

port 5000 now runs http1.x, port 80 continues to run http2

Expose http1.x

---

.github/workflows/release-published.yaml

Fixed a github workflow warning about possible missing value

fixed workflow warning

---

.devcontainer/Dockerfile
.github/workflows/pullrequest-verify.yml
global.json
src/ProjectOrigin.WalletSystem.IntegrationTests/ProjectOrigin.WalletSystem.IntegrationTests.csproj
src/ProjectOrigin.WalletSystem.Server/Dockerfile
src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
src/ProjectOrigin.WalletSystem.Server/Startup.cs

updated to dotnet 8.0

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.open_api_specification_not_changed.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/REST/TransfersControllerTests.cs
src/ProjectOrigin.WalletSystem.Server/CommandHandlers/TransferCertificateCommandHandler.cs
src/ProjectOrigin.WalletSystem.Server/Services/GRPC/WalletService.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ModelsV1.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/TransfersController.cs
src/Protos/wallet.proto

Added REST api to queue a transfer request of a certificate to another wallet for the authenticated user.

Added transfer api to REST endpoint

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.open_api_specification_not_changed.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/REST/ClaimsControllerTests.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ClaimsController.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ModelsV1.cs

Added REST api to queue a claim request of two certificates in a wallet for the authenticated user.

Added claim apis to REST endpoint

---

.devcontainer/Dockerfile
src/ProjectOrigin.WalletSystem.IntegrationTests/GranularCertificateProjectorTests.cs
src/ProjectOrigin.WalletSystem.Server/Projections/GranularCertificateProjector.cs

This pull request adds the GranularCertificateProjectorTests class and fixes a method invocation in the GranularCertificateProjector class.

Add GranularCertificateProjectorTests and fix method invocation in GranularCertificateProjector

---

Makefile
src/ProjectOrigin.WalletSystem.IntegrationTests/TelemetryTest/TelemetryIntegrationTest.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/OpenTelemetryFixture.cs

@ckr123 found that the test still used WireMock, changed the test to use the fixture.

Changed TelemetryTest to use OpenTelemetryFixture

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.can_query_certificates_aggregated.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/CertificatesController.cs
src/ProjectOrigin.WalletSystem.Server/ViewModels/AggregatedCertificatesViewModel.cs

This pull request fixes a bug with a missing mapping in the code. The bug caused incorrect data to be displayed. The fix ensures that the mapping is properly implemented, resulting in accurate data representation.

Fix bug with missing mapping

---

.github/renovate.json

renovate now also discovers if the images in the RegistryFixture should be updated

Add custom manager for Docker image in renovate.json

---

src/ProjectOrigin.WalletSystem.Server/Startup.cs

Reverts project-origin/wallet#362

Revert "add quorum queues"

---

src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/CertificateRepositoryTests.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs

Needs this since the wallet only retries on transient exception

Fixed so that reserve quantity correctly throws transient exception

---

chart/run_kind_test.sh
chart/templates/common/_image.yaml
chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml

Includes fixes for:
- improper indentation
- missing image tags
- warnings about port numbers

Add unit tests for chart

---

src/ProjectOrigin.Vault/Repositories/CertificateRepository.cs

This should make it more clear what goes on

Try catch and logging of QueryMultipleAsync
