.github/workflows/release-helm-chart.yaml

The workflow still had a path from the project-origin/registry repository, this has been fixed to ${{ github.repository }}.

Fix: chart-release workflow

---

.devcontainer/devcontainer.json

Dockerfile build failed locally when downloading Helm. But that should be unrelated to pinning of the dotnet SDK version

Pin devcontainer

---

src/ProjectOrigin.WalletSystem.IntegrationTests/VerifySlicesWorkerTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/WalletSystemTestsBase.cs
src/ProjectOrigin.WalletSystem.Server/BackgroundJobs/VerifySlicesWorker.cs
src/ProjectOrigin.WalletSystem.Server/Extensions/PublicKeyExtensions.cs

The slice verifier now verifies that the received slice publickey matches the key derived from the position.

Fixed VerifySlice now verifies position and key matches

---

charts/project-origin-wallet/templates/deployment-wallet.yaml
charts/project-origin-wallet/values.yaml

The number of wallet containers deployed can now be set using the following in values.yaml file
```yaml
wallet:
replicaCount: 5
```
fixes #84

Added configurable replica count in helm chart

---

.github/workflows/release-published.yaml

Added so the OpenAPI doc is updated when a release is created. 
The release is also updated with a link to the new SwaggerHub site.

Added automated swaggerhub release

---

charts/project-origin-wallet/run_kind_test.sh
charts/project-origin-wallet/templates/deployment-wallet.yaml

This pull request fixes a missing quote around a boolean value and a typo in a test. The missing quote caused an error in the code, while the typo affected the accuracy of the test. These changes ensure that the code functions correctly and the test produces accurate results.

Fix missing quote around boolean and typo in test

---

charts/project-origin-wallet/templates/deployment-wallet.yaml
charts/project-origin-wallet/values.yaml
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.open_api_specification_not_changed.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/Extensions/HttpTaskExtensions.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/AbstractFlowTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/RestFlowTest.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/GrpcTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/REST/SlicesControllerTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/REST/WalletControllerTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/TestServerFixture.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/IHDAlgorithmExtensionsTests.cs
src/ProjectOrigin.WalletSystem.Server/Activities/SendInformationToReceiverWalletActivity.cs
src/ProjectOrigin.WalletSystem.Server/Extensions/IHDAlgorithmExtensions.cs
src/ProjectOrigin.WalletSystem.Server/Options/ServiceOptions.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/IWalletRepository.cs
src/ProjectOrigin.WalletSystem.Server/Repositories/WalletRepository.cs
src/ProjectOrigin.WalletSystem.Server/Serialization/IHDPublicKeyConverter.cs
src/ProjectOrigin.WalletSystem.Server/Services/GRPC/WalletService.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/SlicesController.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
src/ProjectOrigin.WalletSystem.Server/Startup.cs

When updating one must move a variable in the helm chart
```yaml
rest:
basePath: /api
```
has moved to 
```yaml
config:
basePath: /api
```
Added REST apis to enable creation and get of an owners wallet, and creation of wallet-endpoints and external-endpoints.

Added wallet apis to REST endpoint

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.can_query_claims.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/ClaimRepositoryTests.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/MappingExtensions.cs
src/ProjectOrigin.WalletSystem.Server/ViewModels/ClaimViewModel.cs

This pull request fixes the issue with the ClaimViewModel ID property name and updates the mapping accordingly. The ClaimViewModel now uses the correct property name "ClaimId" instead of "Id". This ensures that the ClaimId is properly assigned and used throughout the codebase.

Fix ClaimViewModel ID property name and update mapping

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiBasePathTests.SwaggerJson_VerifyWalletTagContent.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiBasePathTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.open_api_specification_not_changed.verified.txt
src/ProjectOrigin.WalletSystem.IntegrationTests/TelemetryTest/TelemetryIntegrationTest.cs
src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
src/ProjectOrigin.WalletSystem.Server/Services/REST/AddWalletTagDocumentFilter.cs
src/ProjectOrigin.WalletSystem.Server/Startup.cs

As we are slowly beginning to onboard third party clients into the use of the wallet API, we are starting the enrich the OpenApi Specification, with description tags. ```/Wallet``` is the first to receive a description. The goal is to describe the purpose and use case(s), of the API.

Add wallet description tag to OpenApi Spec

---

charts/project-origin-wallet/templates/deployment-wallet.yaml
charts/project-origin-wallet/values.yaml
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/AuthTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/Jwt/JwtTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/JwtTests.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/JwtTokenIssuerFixture.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/TestServerFixture.cs
src/ProjectOrigin.WalletSystem.IntegrationTests/WalletSystemTestsBase.cs
src/ProjectOrigin.WalletSystem.Server/Extensions/JwtBearerOptionsExtensions.cs
src/ProjectOrigin.WalletSystem.Server/Options/JwtOptions.cs
src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/CertificatesController.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ClaimsController.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/TransfersController.cs
src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
src/ProjectOrigin.WalletSystem.Server/Startup.cs

This adds support to verify that the required scopes are  set on the JWT, this is `ENABLED BY DEFAULT` if one wants to disable it, one must do the following in the yaml file
```yaml
config:
jwt:
enableScopeValidation: false
```
- **GET api/v1/wallets**: `po:wallets:read`
- **GET api/v1/wallets/{walletId}**: `po:wallets:read`
- **POST api/v1/wallets**: `po:wallets:create`
- **POST api/v1/wallets/{walletId}/endpoints**: `po:wallet_endpoints:create`
- **POST api/v1/external-endpoints**: `po:external-endpoints:create`
- **GET /api/v1/certificates**: `po:certificates:read`
- **GET /api/v1/aggregate-certificates**: `po:certificates:read`
- **GET /api/v1/claims**: `po:claims:read`
- **GET /api/v1/aggregate-claims**: `po:claims:read`
- **POST /api/v1/claims**: `po:claims:create`
- **GET …

Added scope authentication in wallet

---

charts/project-origin-wallet/Chart.yaml
charts/project-origin-wallet/templates/cnpg-cluster.yaml
charts/project-origin-wallet/templates/deployment-wallet.yaml
charts/project-origin-wallet/templates/migrate-job.yaml
charts/project-origin-wallet/values.yaml

The persistence configuration now includes a BYOD (Bring Your Own Database) option.
This allows the wallet server to connect with an external PostgreSQL databases.
New fields, `secretName` and `secretKey`, have been added under the `persistence.byod` configuration. These fields are used to manage database connection details securely:
- `secretName`: This field is used to specify the name of a Kubernetes Secret that contains the database connection string.
- `secretKey`: This field is used to specify the key within the Kubernetes Secret that contains the connection string.
The variable `persistance` has been renamed to `persistence` to align with the correct spelling.
This change affects the configuration settings for the database in the Project Origin Wallet server.
To ensure seamless …

add-external-postgres-support

---

charts/project-origin-wallet/values.yaml

Problem is that currently helm chart is like: 
```
header:
name:
```
but code has 20+ refferences to 
```
serverFixture.ConfigureHostConfiguration(new()
{
{"auth:type", "header"},
{"auth:header:headerName", HeaderName}
});
}
```
So it would make sense to change it to:
```
header:
headerName:
```

align helm chart with code

---

src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs

This commit updates the `CertificateRepository` by changing the logic for setting the state of wallet slices. Instead of using the `SetWalletSliceState` method, it now directly executes an SQL query to update the `state` column in the `wallet_slices` table. The new query sets the state to `WalletSliceState.Reserved` only if the current state is `WalletSliceState.Available`. If the number of rows changed by the query is not equal to 1, an `InvalidOperationException` is thrown with a corresponding error message.
This change should insure extra  guard against double reserving the same slice.

bug: Added extra guard for reserving slice

---

src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs

This pull request adds the `FOR UPDATE` clause to the SQL queries in the `reserve slices` function. This is done to handle contention issues when multiple transactions try to reserve the same slices simultaneously.

Add FOR UPDATE in reserve slices to handle contention

---

src/ProjectOrigin.WalletSystem.IntegrationTests/ActivityTests/SendInformationToReceiverWalletActivityTests.cs

This pull request adds a WireMockServer for testing the scenario where the external endpoint does not exist in the SendOverRestToExternalWallet_EndpointNotExisting_404 test case. 
The WireMockServer is used to mock the external endpoint and respond with a 404 status code. This ensures that the code handles the scenario correctly.
Previously it used example.com

Add WireMockServer for testing external endpoint in SendOverRestToExternalWallet_EndpointNotExisting_404

---

.devcontainer/devcontainer.json
src/ProjectOrigin.WalletSystem.IntegrationTests/CommandHandlers/ClaimCertificatesCommandHandlerTests.cs
src/ProjectOrigin.WalletSystem.Server/CommandHandlers/ClaimCertificateCommandHandler.cs

ClaimCertificateCommandHandler correctly handles transient exceptions

---

charts/project-origin-wallet/templates/cnpg-cluster.yaml
charts/project-origin-wallet/templates/rabbitmq.yaml

These annotations are done to ensure that rabbitmq and cloudnative PG is not delete when next release will come, where these resources are no longer a part of the chart.

Add resource-policy annotations to rabbitmq and cloudnativepg resources

---

.github/workflows/auto-release.yaml
.github/workflows/release-published.yaml

This pull request adds a new workflow file, auto-release.yaml, that enables automatic releases on Renovate. The workflow is triggered either manually or on a schedule. It checks if a release should be created based on the latest commit and the user who made the commit. If the commit is made by the projectorigin-renovate[bot] user, a new release is created using the previous tag as a starting point. The new version is determined by incrementing the patch number of the previous version. The release artifacts are then built and published.
Additionally, the release-published.yaml workflow file is refactored to include a workflow_dispatch event, allowing manual triggering of the workflow in addition to the existing release event trigger.

Add auto-release workflow and refactor release-published.yaml

---

src/ProjectOrigin.Vault/CommandHandlers/ClaimCertificateCommandHandler.cs
src/ProjectOrigin.Vault/CommandHandlers/TransferCertificateCommandHandler.cs
src/ProjectOrigin.Vault/Startup.cs
test/ProjectOrigin.Vault.Tests/CommandHandlers/ClaimCertificatesCommandHandlerTests.cs
test/ProjectOrigin.Vault.Tests/CommandHandlers/TransferCertificateCommandHandlerTests.cs

Requeue as agressively as we did causes performance issues. With the new approach to finalization, it's no longer needed to requeue and we can keep the messages in front of the queue

Does not requeue reserve errors

---

src/ProjectOrigin.Vault/Activities/SendClaimIntentToChroniclerActivity.cs
src/ProjectOrigin.Vault/RegistryProcessBuilder/Claim.cs
test/ProjectOrigin.Vault.Tests/ActivityTests/SendClaimIntentToChroniclerActivityTests.cs
test/ProjectOrigin.Vault.Tests/CommandHandlers/TransferCertificateCommandHandlerTests.cs
test/ProjectOrigin.Vault.Tests/ExpireTests.cs
test/ProjectOrigin.Vault.Tests/JobTests/ExpireCertificatesJobTests.cs
test/ProjectOrigin.Vault.Tests/RegistryProcessBuilder/ClaimTests.cs

Fix activity, since protobuf.bytestring could not be serialized by masstransit.

Fix SendClaimIntentToChroniclerActivity to use new argument structure

---

src/ProjectOrigin.Vault/Extensions/IItineraryBuilderExtensions.cs
src/ProjectOrigin.Vault/RegistryProcessBuilder/Base.cs

- To minimize the amount of routing slip events and avoid a lot of unroutable messages from events, we only keep the faulted events
- <https://masstransit.io/documentation/concepts/routing-slips#subscriptions>
Unroutable events for the preview enrivonment
https://routingslipevents.p.acorn-dev.dk/admin/thanos/graph?g0.expr=rabbitmq_exchange_messages_unroutable_dropped_total&g0.tab=0&g0.stacked=0&g0.range_input=1d&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=1&g0.store_matches=%5B%5D&g0.engine=prometheus&g0.analyze=0&g0.tenant=
Compared to another preview environment
https://restrictaccessimds.p.acorn-dev.dk/admin/thanos/graph?g0.expr=rabbitmq_exchange_messages_unroutable_dropped_total&g0.tab=0&g0.stacked=0&g0.range_input=1d&g0.max_source_resolution=0s&g0.deduplicate=1&g0 …

Only enable specific routing slip events

---

src/ProjectOrigin.Vault/Database/Postgres/Scripts/v2/v2-0016.sql
src/ProjectOrigin.Vault/Repositories/CertificateRepository.cs

- Optimized QueryAvailableCertificates
- Inlined `certificates_query_model` in the query.
- This allows us to filter before before joins and aggregations (using available_slices and non_withdrawn_certificates). I.e. we have fewer rows to join
- We can also remove the CASE inside the aggregation to get a faster aggregation (the logic is moved to available_slices)
- Added index to optimize queries that need available wallet slices that have a positive quantity

Optimize vault queries
